2023-08-21 20:23:02,749 [INFO] shopapp.views Rendering shop index
2023-08-21 20:23:03,238 [INFO] shopapp.views Rendering shop index
2023-08-21 20:25:10,878 [INFO] django.utils.autoreload /home/artur/PycharmProjects/python_django_logging/logging/mysite/mysite/settings.py changed, reloading.
2023-08-21 20:25:11,658 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-21 20:26:29,501 [INFO] django.utils.autoreload /home/artur/PycharmProjects/python_django_logging/logging/mysite/mysite/settings.py changed, reloading.
2023-08-21 20:26:30,065 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-21 20:26:37,953 [INFO] django.utils.autoreload /home/artur/PycharmProjects/python_django_logging/logging/mysite/mysite/settings.py changed, reloading.
2023-08-21 20:26:38,736 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-22 09:15:44,019 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-22 09:16:06,941 [WARNING] django.request Not Found: /
2023-08-23 09:42:04,496 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-23 09:43:31,660 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-23 09:43:34,682 [WARNING] django.request Not Found: /
2023-08-23 09:43:35,003 [WARNING] django.request Not Found: /favicon.ico
2023-08-23 09:44:25,247 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-23 09:44:27,395 [INFO] shopapp.views Rendering shop index
2023-08-24 00:57:28,029 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 00:57:32,084 [WARNING] django.request Not Found: /
2023-08-24 00:58:31,746 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 00:58:35,707 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 00:58:50,592 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 00:58:52,716 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 00:58:59,240 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 00:59:01,570 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 00:59:11,033 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 00:59:12,496 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 00:59:18,047 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 00:59:20,220 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 00:59:41,473 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 00:59:43,146 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 01:00:02,312 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 01:00:04,424 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 01:00:06,416 [ERROR] django.request Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py", line 143, in get
    elem = products_data[0]
IndexError: list index out of range
2023-08-24 01:13:38,191 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 01:14:17,154 [INFO] django.utils.autoreload C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py changed, reloading.
2023-08-24 01:14:19,435 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 01:15:50,266 [INFO] django.utils.autoreload C:\Python310\Lib\site-packages\urllib3\util\response.py changed, reloading.
2023-08-24 01:15:51,804 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-08-24 01:16:45,604 [WARNING] django.request Not Found: /
2023-08-24 01:16:50,251 [ERROR] django.request Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python310\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\artur\PycharmProjects\Skillbox\python_django_logging\logging\mysite\shopapp\views.py", line 143, in get
    elem = products_data[0]
IndexError: list index out of range
